### ISSUE TITLE
Unable to dump a service container if a parameter is an object or a resource

### ISSUE THREAD

**Issue by jjrumi** [vivait/StringGeneratorBundle#37]
I'm having problems integrating the library with symfony 3.4.
_I had no problems before with Symfony 2.8 and vivait/string-generator-bundle 1.2.3_

Using vivait/string-generator-bundle 2.1.1
Registering the bundle as usual:
```
// AppKernel
public function registerBundles()
{
        $bundles = array(
            ...
            new Vivait\StringGeneratorBundle\VivaitStringGeneratorBundle(),
            ...
        );
}
```

Usage example in one of the entities:
```
    /**
     * @var string
     *
     * @ORM\Column(name="handle", type="string", nullable=false, length=32, unique=true)
     * @Generate(generator="string", options={"length"=32, "chars"="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", "prefix"=""})
     */
    private $handle;
```

Error message:
```
$composer update vivait/string-generator-bundle
...
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

In XmlDumper.php line 362:

  Unable to dump a service container if a parameter is an object or a resource.
```

Error message with a manual addition of a var_dump in XmlDumper.php line 362 to show what's being used:
```
$composer update vivait/string-generator-bundle
...
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
object(Vivait\StringGeneratorBundle\Generator\StringGenerator)#4313 (3) {
  ["length":"Vivait\StringGeneratorBundle\Generator\StringGenerator":private]=>
  int(8)
  ["chars":"Vivait\StringGeneratorBundle\Generator\StringGenerator":private]=>
  string(62) "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  ["prefix":"Vivait\StringGeneratorBundle\Generator\StringGenerator":private]=>
  string(0) ""
}

In XmlDumper.php line 362:

  Unable to dump a service container if a parameter is an object or a resource.
```

**Comment by kieljohn** [comment]
Hi Juan, thanks for the detailed report 👍. We're trying to reproduce the issue on our side ⌛️.

**Comment by kieljohn** [comment]
I believe you're upgrading from v1.x to v2.x of vivait/string-generator-bundle.

There might be some v1.x configuration still present in your `config.yml` files which is causing the issue, it might look like:

```
vivait_string_generator:
  generators:
    string: vivait_generator.generator.string
    secure_bytes: vivait_generator.generator.secure_bytes
    secure_string: vivait_generator.generator.secure_string
```

This configuration was moved to `services.yml` in v2.x which looks something like
```
vivait_generator.generator.secure_bytes:
    class: Vivait\StringGeneratorBundle\Generator\SecureBytesGenerator
    tags:
        - { name: vivait_generator.generator, alias: 'secure_bytes' }
```


❓Could you please migrate your generator configuration from `config.yml` to `services.yml` and let me know how you get along. 

📙 We will be updating our documentation, with an upgrading guide and we will be removing the code that supports the v1.x config.
